# Generated by Django 4.1.3 on 2022-11-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_alter_comment_content_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
