# Generated by Django 4.1.3 on 2022-11-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0009_alter_user_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='email',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='avatar',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
