# Generated by Django 4.1.3 on 2022-11-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0010_user_profile_email_alter_user_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='avatar',
            field=models.CharField(default='https://www.kindpng.com/picc/m/24-248253_user-profile-default-image-png-clipart-png-download.png', max_length=50),
        ),
    ]
