# Generated by Django 4.1.3 on 2022-12-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0011_alter_user_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='email',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='name',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
